export enum ErrorCategory {
  API = 'API_ERROR',
  DATABASE = 'DATABASE_ERROR',
  VALIDATION = 'VALIDATION_ERROR',
  AUTHENTICATION = 'AUTHENTICATION_ERROR',
  AUTHORIZATION = 'AUTHORIZATION_ERROR',
  MONGOOSE = 'MONGOOSE_ERROR',
  UNKNOWN = 'UNKNOWN_ERROR',
}
